[package]
name = "QUIPS"
version = "0.1.0"
edition = "2021"

[dependencies]
iota-client = "1.4.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
hex = "0.4"
